package com.manish.smartcart.shared.model;

import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.SuperBuilder;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.io.Serial;
import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Abstract base entity providing unified primary keys and JPA auditing.
 * Inherited by all domain models to ensure consistent tracking of creation,
 * modification, and optimistic locking across the system.
 */
@Setter
@Getter
@AllArgsConstructor
@NoArgsConstructor
@MappedSuperclass
@SuperBuilder
@EntityListeners(AuditingEntityListener.class)
public abstract class BaseEntity implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;

    // ─── TIER 1: INTERNAL ID ─────────────────────────────────────────────────
    // Strategy: SEQUENCE — each child entity defines its own @SequenceGenerator.
    // allocationSize=50 enables Hibernate batch inserts (50 IDs pre-fetched in memory).
    // NEVER expose this in API responses or frontend URLs.
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "entity_seq")
    private Long id;

    // ─── TIER 2: PUBLIC ID ───────────────────────────────────────────────────
    // Generated by Java (UUID.randomUUID) before the INSERT, not by the DB.
    // This avoids an extra DB round-trip for the sequence call.
    // Used as the external identifier in all REST endpoints: GET /api/v1/orders/{publicId}
    @Column(name = "public_id", updatable = false, nullable = false, unique = true)
    @Builder.Default
    private UUID publicId = UUID.randomUUID();

    // ─── JPA AUDITING ────────────────────────────────────────────────────────
    @CreatedDate
    @Column(name = "created_at", updatable = false, nullable = false)
    private LocalDateTime createdAt;

    @LastModifiedDate
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @CreatedBy
    @Column(name = "created_by", updatable = false)
    private String createdBy;

    @LastModifiedBy
    @Column(name = "modified_by")
    private String modifiedBy;

    // ─── OPTIMISTIC LOCKING ──────────────────────────────────────────────────
    // Prevents the "lost update" problem: if two transactions read v=1 and both
    // try to update, only the first commit succeeds. The second gets
    // OptimisticLockException and retries cleanly. No DB-level row lock needed.
    @Version
    private Long version;

    // ─── EQUALITY ────────────────────────────────────────────────────────────
    // ID-based equality: two entities are the same if their DB-assigned IDs match.
    // Uses publicId as the stable identifier for null-safety before first persist.
    @Override
    public boolean equals(Object obj){
        if(this == obj) return true;
        if(!(obj instanceof BaseEntity that)) return false;
        // Use getter for 'that' to ensure Hibernate proxies are initialized
        return publicId != null && publicId.equals(that.getPublicId());
    }

    @Override
    public int hashCode() {
        // Distribute objects across hash buckets efficiently using the UUID
        return publicId != null ? publicId.hashCode() : getClass().hashCode();
    }
}