-- V44__fix_product_media_public_id_type.sql
-- Fixes an issue where V43 created public_id as VARCHAR(255) instead of UUID,
-- causing Hibernate SchemaValidator/AutoUpdate to fail because BaseEntity expects UUID.

-- 1. Backfill any existing NULL public_ids generated by the V43 migration script
UPDATE product_media SET public_id = gen_random_uuid()::varchar WHERE public_id IS NULL;

-- 2. Safely cast the VARCHAR column to a native PostgreSQL UUID column
ALTER TABLE product_media ALTER COLUMN public_id TYPE UUID USING public_id::uuid;

-- 3. Enforce the NOT NULL and UNIQUE constraints required by BaseEntity
ALTER TABLE product_media ALTER COLUMN public_id SET NOT NULL;
ALTER TABLE product_media ADD CONSTRAINT uk_product_media_public_id UNIQUE (public_id);
